export interface Mentor {
  name: string;
  email: string;
}

export interface ProjectIdea {
  id: string;
  title: string;
  description: string[];
  tasks?: string[];
  size?: 'small' | 'medium' | 'large';
  expectedResults?: string;
  prerequisites?: string;
  skillLevel?: 'beginner' | 'intermediate' | 'advanced';
  mentors: Mentor[];
}

export interface GSoCYear {
  year: number;
  status: 'completed' | 'active' | 'upcoming';
  projects: ProjectIdea[];
}

export const gsoc2022: GSoCYear = {
  year: 2022,
  status: 'completed',
  projects: [
    {
      id: 'htoplogs',
      title: 'Retrospective analysis in htop',
      description: [
        'This project involves advancing the performance analysis capabilities provided by the PCP back end in the classic <a href="https://htop.dev/">htop</a> utility, <a href="https://man7.org/linux/man-pages/man1/htop.1.html">pcp-htop</a>.',
      ],
      tasks: [
        'Implement PCP archive support for historical analysis so that htop can report both live data (as today) and historical system activity (not yet possible) - e.g. displaying system statistics from half an hour ago, yesterday, or even weeks ago. The PCP <a href="https://man7.org/linux/man-pages/man3/PMAPI.3.html">Performance Metrics API</a> provides the retrospective analysis capabilities (on disk storage and query interfaces) we will make use of to provide this functionality.',
        'A new user interface (Screen) in htop for interactively moving the sample time forward or backward and changing the sample interval will be designed and implemented.',
      ],
      size: 'medium',
      expectedResults:
        'New code (C language) will be implemented and submitted to be included in htop that allows the backend platform for PCP to take advantage of <a href="https://man7.org/linux/man-pages/man3/PMAPI.3.html">PMAPI</a> features not yet utilized in the current pcp-htop code.',
      prerequisites: 'C programming, ncurses library knowledge a plus.',
      skillLevel: 'intermediate',
      mentors: [
        { name: 'Ryan Doyle', email: 'ryan@doylenet.net' },
        { name: 'Nathan Scott', email: 'nathans@redhat.com' },
      ],
    },
    {
      id: 'sysstat',
      title: 'Native sysstat PCP tooling',
      description: [
        'The project will be a collaboration between PCP and <a href="http://sebastien.godard.pagesperso-orange.fr">sysstat</a> developers to improve the tooling for users of both projects.',
      ],
      tasks: [
        'Implement support in the sysstat data collector <a href="https://man7.org/linux/man-pages/man8/sadc.8.html">sadc</a> for (optionally) writing PCP archives instead of the traditional sysstat on-disk format. This feature will allow PCP tools like <a href="https://man7.org/linux/man-pages/man1/pmchart.1.html">pmchart</a>, <a href="https://man7.org/linux/man-pages/man1/pmie.1.html">pmie</a>, <a href="https://man7.org/linux/man-pages/man1/pmrep.1.html">pmrep</a> and many others to directly analyze data generated by sadc. sysstat users will also be able to visualize their data in <a href="https://grafana.com/">Grafana</a> as its being written to disk, using the <a href="https://grafana-pcp.readthedocs.io/">grafana-pcp</a> module.',
        'Make use of the <a href="https://man7.org/linux/man-pages/man3/PMAPI.3.html">PMAPI</a> to allow the sysstat analysis utilities, namely <a href="https://man7.org/linux/man-pages/man1/cifsiostat.1.html">cifsiostat</a>, <a href="https://man7.org/linux/man-pages/man1/iostat.1.html">iostat</a>, <a href="https://man7.org/linux/man-pages/man1/mpstat.1.html">mpstat</a>, <a href="https://man7.org/linux/man-pages/man1/pidstat.1.html">pidstat</a>, and <a href="https://man7.org/linux/man-pages/man1/tapestat.1.html">tapestat</a> to access this historical data. Code changes to each of these utilities will be required to implement the PCP archive support using the <a href="https://man7.org/linux/man-pages/man3/PMAPI.3.html">PCP performance metrics API</a>.',
      ],
      size: 'large',
      expectedResults:
        'After cross-project collaboration and design, extensions to the sysstat collector and analysis utilities will be designed and implemented, unit tests and documentation will be written.',
      prerequisites: 'C programming, operating systems',
      skillLevel: 'intermediate',
      mentors: [
        { name: 'Sebastien Godard', email: 'sysstat@orange.fr' },
        { name: 'Steve Kay', email: 'stevekay@gmail.com' },
        { name: 'Nathan Scott', email: 'nathans@redhat.com' },
      ],
    },
    {
      id: 'htoptabs',
      title: 'Generalized columns in htop',
      description: [
        'The <a href="https://htop.dev/">htop</a> utility recently acquired the ability to display multiple <a href="https://hisham.hm/img/htop-tabs.png">Tabs</a> in its user interface. Currently these display only process information. The aim of this project is to support generalized Tabs, where information beyond processes can be displayed in columns.',
      ],
      tasks: [
        'Extend htop Tabs to provide a more generalized Tab and Columns concept, such that top-most resource utilization for system objects other than processes can be displayed.',
        'The addition of a Tab for Linux cgroup metrics would be an excellent way to visually demonstrate this idea.',
        'Extend pcp-htop tabs to allow loading at runtime from (text-based) configuration files. This is conceptually similar to the dynamic Meter and Column configuration available in htop today.',
        'The ability to configure a dynamic Tab for PCP eBPF metrics would be an excellent outcome.',
      ],
      size: 'medium',
      expectedResults:
        'New code (C language) will be implemented that provides dynamically configurable tabs in htop.',
      prerequisites: 'C programming, ncurses library knowledge a plus.',
      skillLevel: 'intermediate',
      mentors: [
        { name: 'Benny Baumann', email: 'benbe@geshi.org' },
        { name: 'Nathan Scott', email: 'nathans@redhat.com' },
        { name: 'Andreas Gerstmayr', email: 'agerstmayr@redhat.com' },
      ],
    },
    {
      id: 'series',
      title: 'Query language extension and new functions',
      description: [
        'Performance Co-Pilot timeseries are series of time-stamped values gathered centrally from hosts making performance data available. This data could be gathered for many metrics, at high frequency, and from many hosts. It is potentially high volume data, and searching it efficiently (querying) at speed is a non-trivial problem.',
        'The Performance Co-Pilot timeseries query language is designed to allow fast querying based on metric names and labels. A command line utility and a REST API are available from <a href="https://man7.org/linux/man-pages/man1/pmseries.1.html">pmseries</a> and the <a href="https://man7.org/linux/man-pages/man1/pmproxy.1.html">pmproxy</a> daemon. The existing query language implementation is now maturing, however there are some important new functions needed along with related grammar extensions.',
      ],
      tasks: [
        'grammar extensions supporting scalar operands in expressions, either as literal constants or from functions returning a scalar result.',
        'additional functions complementing existing functions to operate across both the time domain (with one scalar result per metric instance) and across instance domains (with a single vector result).',
        'new statistical functions such as top_k(expr) and nth_percentile(expr, n) and rolling_avg(expr, n).',
        'new functions for subsampling and interpolation of vector operands to match time series samples with other vector operands in an expression.',
      ],
      size: 'large',
      expectedResults:
        'Our new contributor will extend their C language programming skills, learn about the <a href="https://en.wikipedia.org/wiki/Yacc">yacc</a> language parsing tool, performance analysis with Performance Co-Pilot and the <a href="https://redis.io/">Redis</a> distributed data store. They will also collaborate and participate in a vibrant open-source environment with very experienced engineers and performance analysts.',
      prerequisites: 'C programming.',
      skillLevel: 'advanced',
      mentors: [
        { name: 'Kyoma Zhang', email: 'kyomazhang@gmail.com' },
        { name: 'Nathan Scott', email: 'nathans@redhat.com' },
      ],
    },
    {
      id: 'htopgraphs',
      title: 'Graphing in htop',
      description: [
        'Using braille characters from Unicode it is possible to produce <a href="https://user-images.githubusercontent.com/970853/93331430-827b9300-f820-11ea-8f44-d2f784073e2c.png">beautiful</a> <a href="https://user-images.githubusercontent.com/2487263/127462685-9f75f527-986e-49b7-802d-95472fd2b973.png">graphs</a> for console tools like the classic <a href="https://htop.dev/">htop</a> utility. Prototype implementations have shown this is feasible but substantial (re)work is needed to make this production ready.',
      ],
      tasks: [
        'Work with htop community developers to implement, test and finally merge this much sought-after feature.',
        'Following a review of the existing implementations, a new design will be produced and implemented pulling the best of the existing ideas into a robust, complete version.',
      ],
      size: 'medium',
      expectedResults: 'Beautiful graphs for the graph meter mode of htop.',
      prerequisites: 'C programming, ncurses library knowledge a plus.',
      skillLevel: 'intermediate',
      mentors: [
        { name: 'Benny Baumann', email: 'benbe@geshi.org' },
        { name: 'Nathan Scott', email: 'nathans@redhat.com' },
      ],
    },
  ],
};
