# Non pcp man pages which must be redirected externally
ext_manpages = [
    'archive::zip', 'asctime', 'atexit', 'atop', 'autofs', 'autofsd',
    'avahi-daemon', 'awk', 'bash', 'bcc', 'bpf',
    'byteorder', 'bzip2', 'calloc', 'cat', 'certutil',
    'chkconfig', 'clock_gettime', 'close', 'collectl', 'connect', 'cpp',
    'cron', 'crontab', 'ctime', 'date', 'date::format', 'date::parse',
    'datetime', 'dbi', 'dlopen', 'dso', 'egrep', 'environ', 'exec',
    'execve', 'exit', 'file', 'find', 'fork', 'fprintf', 'free', 'freopen',
    'fwrite', 'gdb', 'getenv', 'getgrent', 'gethostbyname', 'gethostname',
    'getopt', 'getopt_long', 'getpwent', 'gettimeofday', 'glob',
    'gluster', 'gzip',
    'hostname', 'htonl', 'httpd', 'ibnetdiscover', 'ifenslave', 'insight',
    'inventor', 'iostat', 'ivview', 'journalctl', 'kill', 'killall', 'kvm',
    'ldapsearch', 'ln', 'local', 'localtime', 'logger', 'logconv.pl', 'make',
    'malloc', 'mkstemp', 'mktemp', 'mktime', 'mountstats', 'mount.cifs',
    'mrtg',
    'named', 'named.conf', 'nanosleep', 'nfs', 'nsd', 'ns-slapd',
    'nslookup', 'numastat', 'ole::storage_lite', 'perl',
    'perror', 'pipe', 'printf', 'putenv', 'python', 'qshape', 'rc0', 'rc2',
    'read', 'readline', 'realloc', 'redis-cli', 'redis-server',
    'regcmp', 'regcomp', 'regex', 'resolver',
    'rld', 'rpc', 'rpm', 'rpcbind', 'rsync', 'rsyslogd', 'rsyslog.conf',
    'sadc', 'sadf', 'samba', 'smbd', 'sar', 'sed', 'select', 'sendmail',
    'setitimer', 'seteuid', 'setegid', 'sh', 'showrgb', 'sleep', 'socket',
    'spreadsheet::parseexcel', 'spreadsheet::readsxc', 'spreadsheet::xlsx',
    'sprintf', 'sscanf', 'stap', 'stdio', 'strdup', 'strerror', 'strftime',
    'strtod', 'strtol', 'sum', 'syslogd', 'tail', 'telnet', 'text::csv_xs',
    'top', 'tsocks', 'tzselect', 'uptime', 'varargs', 'waitpid',
    'write', 'x', 'xconfirm', 'xmessage',
    'xml::tokeparser', 'xvfb', 'xwsh', 'xz', 'ypcat' ]
